### ISSUE TITLE
Tag for 0.12.2.3

### ISSUE THREAD

**Issue by wemersonjanuario** [h4cc/wkhtmltopdf-amd64#10]
Could you generate tag for 0.12.2.3 release?

**Comment by h4cc** [comment]
Thanks for the hint.

But the version 0.12.2.3 is a windows only release. Links on the download page still go to 0.12.2.1 for non windows builds: http://wkhtmltopdf.org/downloads.html

**Comment by wemersonjanuario** [comment]
ohh, sorry, I did not see about windows only. So I  will update my package  based on yours.
https://github.com/wemersonjanuario/wkhtmltopdf-windows. Thanks.
