### ISSUE TITLE
libjpeg old version (libjpeg.so.8)

### ISSUE THREAD

**Issue by ChenOhayon** [h4cc/wkhtmltopdf-amd64#11]
Hi,

The wkhtmltopdf-amd64 binary is compiled with an old version of libjpeg:
```
ldd wkhtmltopdf-amd64 | grep libjpeg
./wkhtmltopdf-amd64: /usr/lib64/libjpeg.so.8: version `LIBJPEG_8.0' not found (required by ./wkhtmltopdf-amd64)
	libjpeg.so.8 => /usr/lib64/libjpeg.so.8 (0x00007f92f09dd000)
```  
Latest version of libjpeg is 62 (libjpeg.so.62).

Is there any workaround for this?
Or maybe you can compile the binary with the latest version of libjpeg?

Will be glad for any help.
Thanks ahead!
Chen

**Comment by h4cc** [comment]
Thanks for the hint. But i did not compile wkhtmltopdf myself - i simply took the binary from a `.deb` package.

Please report your issue here, where the original developers are: https://github.com/wkhtmltopdf/wkhtmltopdf

**Comment by ChenOhayon** [comment]
Ok, thanks for the quick response!
