### ISSUE TITLE
Unable to load library icui18n

### ISSUE THREAD

**Issue by janzenz** [h4cc/wkhtmltopdf-amd64#12]
I get this error:

`The exit status code '1' says something went wrong:
stderr: "Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)" `

OS: ubuntu1404-x64
wkhtmltopdf: 0.12.2.1

I tried

`apt-get icui18n` but ubuntu can't find that package. I also tried using this fix https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2242 but the answer was to download `wkhtmltopdf` via `apt-get`. Is there a better solution?

**Comment by h4cc** [comment]
The binary in this package was compiled for Debian, not Ubuntu. It is also not static linked and errors like yours might occur.

Installing wkhtmltopdf on the system is the best solution anyway.

More info in the FAQ: http://wkhtmltopdf.org/downloads.html#faq

**Comment by shaneparsons** [comment]
@h4cc Do you currently have any plans to make a ubuntu package?
