### ISSUE TITLE
Packages for Debian Jessie

### ISSUE THREAD

**Issue by slashsBin** [h4cc/wkhtmltopdf-amd64#13]
Are there any plans on upgrading packages to Debian Stable(Jessie)?

**Comment by h4cc** [comment]
Debian Jessie 8 is stable since April, a upgrade seems usefull.

Problem currently lies in the versioning of this package, which is equal to the versioning of wkhtmltopdf.
This disallows having a newer version or different ones for multiple architectures.

How about adding all Debian/Ubuntu/OSX binaries with names like `wkhtmltopdf-amd64-debian-jessie`?

**Comment by slashsBin** [comment]
I don't think adding all binaries is a good idea, because doing so will force everyone to have all binaries in their vendor directory. For example I'd like to use wkhtmltopdf on my debian jessie server, so I add it to my `composer.json` file and do a `composer update`, but all other binaries will also be downloaded to my vendor directory. It will increase network transfer rate on every `composer install` and `composer update`, and also increase my project backup size.
I don't have a good alternative solution for this, but it seems having multiple git branches for every distribution will do the job, or maybe multiple forks of this repository.

**Comment by h4cc** [comment]
In the end only a different package will solve this. But with Debian/Ubuntu/CentOS/OSX this would result in a total of 8 packages (=repos).
That is not what this was intended so solve and would require some tedious work by now.

Also the wkhtmltopdf project now offers .deb/.rpm/.pkg/.exe installer/packages, which solve its correctly via package manager plus integrated security features.
If there ain't a better idea, i will only provide Debian 7 binaries here - anybody else should not rely on this but use the original packages.

Thanks for your feedback! :+1:
