### ISSUE TITLE
Binaries for Debian 8 (Jessie)

### ISSUE THREAD

**Issue by alterphp** [h4cc/wkhtmltopdf-amd64#15]
Hi,

This is not an issue but a suggestion : do you plan to provide wkhtmlto* binaries for Debian 8 (Jessie) ?

Best regards,

**Comment by mdPlusPlus** [comment]
Please do so. I haven't found a way to fix the "libjpeg.so.8" error on Jessie myself, yet.
Can anyone point me in the right direction?

**Comment by h4cc** [comment]
Thanks for your questions and feedback.

Using this package is just a unrecommended "workaround". If you do not have a fitting target system this package should be avoided. Installing wkhtmltoX directly on your system ist often the best approach.
