### ISSUE TITLE
Update to latest wkhtmltopdf

### ISSUE THREAD

**Issue by majksner** [h4cc/wkhtmltopdf-amd64#16]
New version of wkhtmltopdf is out.

**Comment by zendre4** [comment]
+1

**Comment by adrienfichet** [comment]
:+1:

**Comment by zendre4** [comment]
I open a PR, we just have to wait for the response...

**Comment by h4cc** [comment]
Thanks for the hint. I updated all the binaries and released them using version 0.12.3.
