### ISSUE TITLE
config for knpsnappy bundle

### ISSUE THREAD

**Issue by apfz** [h4cc/wkhtmltopdf-amd64#9]
What should the link to the binary be, when configuring knpsnappy?
Currently I have:
```
knp_snappy:
        pdf:
            enabled:    true
            binary:     "%kernel.root_dir%/../bin/wkhtmltopdf-amd64"
            options:    []
        image:
            enabled:    false
            binary:     "%kernel.root_dir%/../bin/wkhtmltoimage-amd64"
            options:    []
```
Is that correct?

Doing this, is giving me a permission denied error when knpsnappy tries to use the binary. should there be some instructuions for this in your installation guide?

Furthermore there is a type I believe in the install guide where it says /vendor/bin....

**Comment by h4cc** [comment]
The directory where composer will put binaries depend on your `bin-dir` setting in `composer.json`: https://getcomposer.org/doc/articles/vendor-binaries.md

Also try to check, if the binaries are executeable. If not fix that using `chmod` or such.
